#Start with a base image containing Java runtime
FROM openjdk:17-jdk-slim

#Information around who maintains the image
MAINTAINER eazybytes.com

# Add the application's jor to the image
COPY build/libs/cards-0.0.1-SNAPSHOT.jar cards-0.0.1-SNAPSHOT.jar

# Install curl (or any other necessary tools)
RUN apt-get update && apt-get install -y curl

# java -jar  build/libs/accounts-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "cards-0.0.1-SNAPSHOT.jar"]


