services:
  network-deploy-service:
    network:
      - eazybank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extend:
      services: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/