@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.easybyte.accounts.controller.AccountController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_769133558 { 
   	label=easybyte
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1498588490 { 
   	label=accounts
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AccountController283915277[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AccountController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   accountService: IAccountService [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createAccount(customer: CustomerDto): ResponseEntity&lt;ResponseDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteAccount(phoneNumber: String): ResponseEntity&lt;ResponseDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ fetchAccountDetails(phoneNumber: String): ResponseEntity&lt;CustomerDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ up(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateAccount(customerDto: CustomerDto): ResponseEntity&lt;ResponseDto&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AccountServiceImpl109431318[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AccountServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   accountRepository: AccountRepository [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   customerRepository: CustomerRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createAccount(customerdto: CustomerDto)</TD></TR>
<TR><TD ALIGN="LEFT" >- createNewAccount(customer: Customer): Accounts</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteAccount(phoneNumber: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ fetchAccountDetails(phoneNumber: String): CustomerDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateAccount(customerDto: CustomerDto): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AccountsMapper712151246[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AccountsMapper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ mapToAccounts(accountsDto: AccountsDto, accounts: Accounts): Accounts</TD></TR>
<TR><TD ALIGN="LEFT" >+ mapToAccountsDto(accounts: Accounts, accountsDto: AccountsDto): AccountsDto</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CustomerMapper712151246[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CustomerMapper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ mapToCustomer(customerDto: CustomerDto, customer: Customer): Customer</TD></TR>
<TR><TD ALIGN="LEFT" >+ mapToCustomerDo(customer: Customer, customerDto: CustomerDto): CustomerDto</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
AccountController283915277 -> AccountServiceImpl109431318[arrowhead=none];
    
}
@enduml