@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.easybyte.accounts.controller.AccountController#updateAccount(CustomerDto)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.easybyte.accounts.controller.AccountController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_769133558 { 
   	label=easybyte
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1498588490 { 
   	label=accounts
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1474019816 { 
   	label=AccountController
	labeljust=l
	fillcolor=white
	style=filled
   
   AccountController283915277XXXupdateAccount104218367[
	label="+ updateAccount()"
	style=filled
	fillcolor=white
	tooltip="AccountController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1570125339 { 
   	label=CustomerMapper
	labeljust=l
	fillcolor=white
	style=filled
   
   CustomerMapper712151246XXXmapToCustomer1084593869[
	label="+ mapToCustomer()"
	style=filled
	fillcolor=white
	tooltip="CustomerMapper

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_170347555 { 
   	label=AccountsMapper
	labeljust=l
	fillcolor=white
	style=filled
   
   AccountsMapper712151246XXXmapToAccounts217434573[
	label="+ mapToAccounts()"
	style=filled
	fillcolor=white
	tooltip="AccountsMapper

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_806818988 { 
   	label=AccountServiceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   AccountServiceImpl109431318XXXupdateAccount104218367[
	label="+ updateAccount()"
	style=filled
	fillcolor=white
	tooltip="AccountServiceImpl

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AccountController283915277XXXupdateAccount104218367 -> AccountServiceImpl109431318XXXupdateAccount104218367;
AccountServiceImpl109431318XXXupdateAccount104218367 -> AccountsMapper712151246XXXmapToAccounts217434573;
AccountServiceImpl109431318XXXupdateAccount104218367 -> CustomerMapper712151246XXXmapToCustomer1084593869;
    
}
@enduml