services:
  configserver:
    image: "npdangkhoa/configserver:${MS_VERSION}"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: network-deploy-service

  eurekaserver:
    image: "npdangkhoa/eurekaserver:${MS_VERSION}"
    container_name: "eurekaserver-ms"
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config


  accounts:
    image: "npdangkhoa/accounts:${MS_VERSION}"
    container_name: "accounts-ms"
    ports:
      - "9094:9094"
    healthcheck:
      test: "curl --fail --silent localhost:9094/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SERVER_PORT: 9094
    extends:
      file: common-config.yaml
      service: microservice-eurekaserver-config

  loans:
    image: "npdangkhoa/loans:${MS_VERSION}"
    container_name: "loans-ms"
    ports:
      - "9091:9091"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SERVER_PORT: 9091
    healthcheck:
      test: "curl --fail --silent localhost:9091/actuator/health/readiness | grep UP  || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-eurekaserver-config

  cards:
    image: "npdangkhoa/cards:${MS_VERSION}"
    container_name: "cards-ms"
    ports:
      - "9093:9093"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SERVER_PORT: 9093
    healthcheck:
      test: "curl --fail --silent localhost:9093/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-eurekaserver-config

  gatewayserver:
    image: "npdangkhoa/gatewayserver:${MS_VERSION}"
    container_name: "gatewayserver-ms"
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-eurekaserver-config
networks:
  eazybank: