management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enable: true
    liveness-state:
      enable: true
  endpoint:
    health:
      probes:
        enabled: true