load('@bazel_tools//tools/build_defs/repo:http.bzl', 'http_archive')

RULES_JVM_EXTERNAL_TAG = '4.1'
RULES_JVM_EXTERNAL_SHA = 'f36441aa876c4f6427bfb2d1f2d723b48e9d930b62662bf723ddfb8fc80f0140'

http_archive(
    name = 'rules_jvm_external',
    strip_prefix = 'rules_jvm_external-%s' % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = 'https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip' % RULES_JVM_EXTERNAL_TAG,
)

# This code tells Bazel to install a new repository rule found at 
#https://github.com/bazelbuild/rules_jvm_external/archive/4.1.zip and name it rules_jvm_external.
# This rule knows how to retrieve dependencies from Maven.

#The next step is to tell Bazel which dependencies we want. 
#We can do it by adding this in the same file:

load('@rules_jvm_external//:defs.bzl', 'maven_install')

maven_install(
    artifacts = [
        'org.junit.jupiter:junit-jupiter-api:5.7.1',
    ],
    repositories = [
        'https://repo1.maven.org/maven2',
    ],
)

