build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related Local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345


info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"